#!/usr/bin/env bash

case "$1" in
  wget2) : 'pkg'
    case "$2" in
      "")
        exit 0
      ;;
      latest)
        echo "2.2.0" && exit 0
      ;;
      2.2.0) : 'ver'
        case "$3" in
          src) echo "https://ftp.gnu.org/gnu/wget/wget2-2.2.0.tar.gz" ;;
          dst) echo "wget2-2.2.0" ;;
          bld) echo "gnu" ;;
        esac
        exit 0
      ;;
      *)
        exit 1
      ;;
    esac
  ;;
  lzip) : 'pkg'
    case "$2" in
      "")
        exit 0
      ;;
      latest)
        echo "1.25" && exit 0
      ;;
      1.25) : 'ver'
        case "$3" in
          src) echo "https://download.savannah.gnu.org/releases/lzip/lzip-1.25.tar.gz" ;;
          dst) echo "lzip-1.25" ;;
          bld) echo "gnu" ;;
        esac
        exit 0
      ;;
      *)
        exit 1
      ;;
    esac
  ;;
  gnu-coreutils) : 'pkg'
    case "$2" in
      "")
        exit 0
      ;;
      latest)
        echo "9.6" && exit 0
      ;;
      9.6) : 'ver'
        case "$3" in
          src) echo "https://ftp.gnu.org/gnu/coreutils/coreutils-9.6.tar.gz" ;;
          dst) echo "coreutils-9.6" ;;
          bld) echo "gnu" ;;
        esac
        exit 0
      ;;
      *)
        exit 1
      ;;
    esac
  ;;
  gnu-ed) : 'pkg'
    case "$2" in
      "")
        exit 0
      ;;
      latest)
        echo "1.21.1" && exit 0
      ;;
      1.21.1) : 'ver'
        case "$3" in
          src) echo "https://ftp.wayne.edu/gnu/ed/ed-1.21.1.tar.lz" ;;
          dst) echo "ed-1.21.1" ;;
          bld) echo "gnu" ;;
        esac
        exit 0
      ;;
      *)
        exit 1
      ;;
    esac
  ;;
  gnu-spell) : 'pkg'
    case "$2" in
      "")
        exit 0
      ;;
      latest)
        echo "1.1" && exit 0
      ;;
      1.1) : 'ver'
        case "$3" in
          src) echo "https://ftp.gnu.org/gnu/spell/spell-1.1.tar.gz" ;;
          dst) echo "spell-1.1" ;;
          bld) echo "gnu" ;;
        esac
        exit 0
      ;;
      *)
        exit 1
      ;;
    esac
  ;;
  *)
    exit 1
  ;;
esac
