#!/usr/bin/env bash

case "$1" in
  wget2) : 'pkg'
    case "$2" in
      "")
        exit 0
      ;;
      latest)
        printf "%q" "2.2.0" && exit 0
      ;;
      2.2.0) : 'ver'
        case "$3" in
          src) printf "%q" "https://ftp.gnu.org/gnu/wget/wget2-2.2.0.tar.gz" ;;
          dst) printf "%q" "wget2-2.2.0" ;;
          bld) printf "%q" "gnu" ;;
        esac
        exit 0
      ;;
      *)
        exit 1
      ;;
    esac
  ;;
  lzip) : 'pkg'
    case "$2" in
      "")
        exit 0
      ;;
      latest)
        printf "%q" "1.25" && exit 0
      ;;
      1.25) : 'ver'
        case "$3" in
          src) printf "%q" "https://download.savannah.gnu.org/releases/lzip/lzip-1.25.tar.gz" ;;
          dst) printf "%q" "lzip-1.25" ;;
          bld) printf "%q" "gnu" ;;
        esac
        exit 0
      ;;
      *)
        exit 1
      ;;
    esac
  ;;
  gnu-coreutils) : 'pkg'
    case "$2" in
      "")
        exit 0
      ;;
      latest)
        printf "%q" "9.6" && exit 0
      ;;
      9.6) : 'ver'
        case "$3" in
          src) printf "%q" "https://ftp.gnu.org/gnu/coreutils/coreutils-9.6.tar.gz" ;;
          dst) printf "%q" "coreutils-9.6" ;;
          bld) printf "%q" "gnu" ;;
        esac
        exit 0
      ;;
      *)
        exit 1
      ;;
    esac
  ;;
  gnu-ed) : 'pkg'
    case "$2" in
      "")
        exit 0
      ;;
      latest)
        printf "%q" "1.21.1" && exit 0
      ;;
      1.21.1) : 'ver'
        case "$3" in
          src) printf "%q" "https://ftp.wayne.edu/gnu/ed/ed-1.21.1.tar.lz" ;;
          dst) printf "%q" "ed-1.21.1" ;;
          bld) printf "%q" "gnu" ;;
        esac
        exit 0
      ;;
      *)
        exit 1
      ;;
    esac
  ;;
  gnu-spell) : 'pkg'
    case "$2" in
      "")
        exit 0
      ;;
      latest)
        printf "%q" "1.1" && exit 0
      ;;
      1.1) : 'ver'
        case "$3" in
          src) printf "%q" "https://ftp.gnu.org/gnu/spell/spell-1.1.tar.gz" ;;
          dst) printf "%q" "spell-1.1" ;;
          bld) printf "%q" "gnu" ;;
        esac
        exit 0
      ;;
      *)
        exit 1
      ;;
    esac
  ;;
  *)
    exit 1
  ;;
esac
