#!/usr/bin/env bash

readonly JPW="/var/lib/jpw"
readonly PKG="$JPW/pkg"
readonly DBA="$JPW/available"
readonly DBI="$JPW/installed"

function rooted {
  return $(( EUID == 0 ? 0 : 1 ))
}

function warn {
  echo "warning: $1"
}

function fail {
  echo "error: $1"
  exit 1
}

function download {
  if [[ -n $2 ]]; 
    then wget "$1" -q --show-progress --progress=bar:force:noscroll --no-cache -O "$2"
    else wget "$1" -q --show-progress --progress=bar:force:noscroll --no-cache
  fi

  case $? in
    4 ) fail "network failure" ;;
    8 ) fail "failed to retrieve $1" ;;
  esac
}

function cmd::help {
  echo "jpw 2025.03.27, a coreutils-based package manager for GNU/Linux"
  echo
  echo "usage: $program <command>"
  echo
  echo "commands:"
  echo "  help          display this help text and quit"
  exit 0
}

function cmd::update {
  if ! rooted; then
    fail "cannot update without root privilege"
  fi

  download https://raw.githubusercontent.com/jonathanpwalton/jpw/main/available $DBA
}

function main () {
  local program=$0
  local command=$1; shift

  if rooted; then
    mkdir -p $PKG
  fi

  case "$command" in
    update ) cmd::update "$@" ;;
    help ) cmd::help "$@" ;;
    * ) fail "missing or invalid command, see '$program help' for more information" ;;
  esac
}

main "$@"
