#!/usr/bin/bash

NAME="jpw"
VERSION="0.0.1"
DESCRIPTION="a simple build-from-source package manager for GNU/Linux"

commands=(
	["help"]="display this help text and exit"
	["install"]="install a package"
	["uninstall"]="uninstall a package"
)

error () {
	echo "error: $1"
	exit 1
}

require_root () {
	if [ "$EUID" -ne 0 ]; then
		error "you cannot use this command unless you are root"
	fi
}

usage () {
	echo "${NAME} ${VERSION}, ${DESCRIPTION}"
	echo "usage: $0 <command>"
	exit 0
}

if [ -z "$1" ]; then
	error "command not supplied, try '$0 help' for more information"
elif [ "$1" == "help" ]; then
	usage
elif [ "$1" == "install" ]; then
	shift
	require_root
	
	while (("$#")); do
		IFS=":" read -ra pkg_ver <<< "$1"

		if [ -z "${pkg_ver[1]}" ]; then
			pkg_ver[1]="latest"
		fi

		echo "${pkg_ver[*]}"

		shift
	done

else
	error "invalid command '$1', try '$0 help' for more information"
fi

: '
mapfile LINES < /testing
declare -A INSTALLED

for i in "${LINES[@]}"; do
	IFS=':' read -ra LINE <<< $i
	INSTALLED[${LINE[0]}]=${LINE[1]}
done

for i in "${!INSTALLED[@]}"; do
  echo "key  : $i"
  echo "value: ${INSTALLED[$i]}"
done

if [ "${INSTALLED[spell]+1}" == "1" ]; then
	echo "hi"
fi
'