#!/usr/bin/env bash

if [ "$1" == "name" ]; then
	echo "gnu-ed"
elif [ "$1" == "latest" ]; then
	echo "1.21.1"
elif [ "$1" == "versions" ]; then
	if [ -z "$2" ]; then
		echo "1.21.1"
	elif [ "$2" == "1.21.1" ]; then
		if [ "$3" == "src" ]; then
			echo "https://ftp.wayne.edu/gnu/ed/ed-1.21.1.tar.lz"
		elif [ "$3" == "dst" ]; then
			echo "ed-1.21.1"
		elif [ "$3" == "build" ]; then
			echo "gnu"
		fi
	fi
fi
