#!/usr/bin/env bash

if [ "$1" == "name" ]; then
	echo "lzip"
elif [ "$1" == "latest" ]; then
	echo "1.25"
elif [ "$1" == "versions" ]; then
	if [ -z "$2" ]; then
		echo "1.25"
	elif [ "$2" == "1.25" ]; then
		if [ "$3" == "src" ]; then
			echo "https://download.savannah.gnu.org/releases/lzip/lzip-1.25.tar.gz"
		elif [ "$3" == "dst" ]; then
			echo "lzip-1.25"
		elif [ "$3" == "build" ]; then
			echo "gnu"
		fi
	fi
fi
